name: using-lfs-caching
on:
  workflow_dispatch:
jobs:
  lfs-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create LFS file list
        run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id; cat .lfs-assets-id

      - name: LFS Cache
        id: cache-lfs
        uses: actions/cache@v3
        with:
          path: lfs/
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: |
            ${{ runner.os }}-lfs-

      - name: Git LFS Pull
        run: git lfs pull
        env:
          GIT_TRACE: 1

      - name: Print csv content 
        run: python csv_reader.py
        shell: bash
